### ISSUE TITLE
Truncated height in displaying long latex formulas

### ISSUE THREAD

**Issue by aarjan** [shahxadakram/flutter_tex#7]
While trying to display long forumulas with multiple webviews using this package, the text are truncated. 
I think, the container takes the plain text height before the forumula is rendered, so the new rendered value is truncated.

**Comment by shahxadakram** [comment]
How are you using multiple webview??

**Comment by Vinoth1094** [comment]
Hi, we are loading multiple WebViews inside a ListView. In order to use the TeXView inside lost, we need to wrap it inside a fixed height widget. The issue is that WebView has onPageFinished callback which we are able to use to find the height of the WebView. But in TeXView there is no such callback. So is it possible to calculate the height of the TeXView after rendering?

**Comment by shahxadakram** [comment]
Hey I have added `onPagedFinished` callback to the `TeXView`, hope it would solve your issue.. you should update it to latest version [flutter_tex-1.0.1](https://pub.dev/packages/flutter_tex#-changelog-tab-)

**Comment by shahxadakram** [comment]
> Hi, we are loading multiple WebViews inside a ListView. In order to use the TeXView inside lost, we need to wrap it inside a fixed height widget. The issue is that WebView has onPageFinished callback which we are able to use to find the height of the WebView. But in TeXView there is no such callback. So is it possible to calculate the height of the TeXView after rendering?

would you like to share, how are you finding height of  WebView?

**Comment by Vinoth1094** [comment]
> would you like to share, how are you finding height of WebView?

double height = double.parse(await _listController[index].evaluateJavascript("document.documentElement.scrollHeight;"));

I've tried exposing onPageFinished callback manually already. But the issue is after rendering the formulas the height gets increased than calculated one.
Also getting "Failed to create server socket" error always.

**Comment by shahxadakram** [comment]
I have updated the package with `onRenderFinished` callback with calculated height, just check that.
